### ISSUE TITLE
Communication about the project

### ISSUE THREAD

**Issue by codec-abc** [skiplang/skip#27]
Hi,

This project seems really interesting. As such I would like to know more about it.

It seems that some members of the core (previously at Facebook) hang around here. If this is the case, can one of them communicate (a bit more) about the language. For example: 

Do they have any plan to continue to work on it? If yes, what features are planned? Do they have a vision for the future of the language? If no, do they plan to give away the ownership of the repository? etc...

**Comment by pikatchu** [comment]
Hey! Thanks for reaching out.

Skip will no longer be developed at Facebook, but I plan to keep on working on it. There are already some people who offered to help me.

What I want to do next:
- Make the rest of the compiler incremental. So right now, the front-end is incremental when you use the skip_server, which means that you get type-checking errors in a few milliseconds, even on a large code base. But the rest of the compiler is not. So re-compiling typically takes a few seconds. I really would like to make that faster, so that iterating on Skip is always instantaneous.
- Cleanup the repo. It takes too long to build, and the build system is too complicated. The reason why things are the way they are is because we were planning to interop with Hack and HHVM. For the interop to work well, we needed to be fully integrated to the HHVM repo. So that meant, using Cmake etc ... Given that this interop doesn't need to be maintained, we should be able to simplify things.

So that's what I plan to do short term. Regarding the language, I highly doubt it is going to change much. The language has been stable for a while within FB (I would say for around a year). I tend to be extremely conservative with language changes because it always has unintended consequences that are difficult to fully predict.

In general, I just push back on complexity when it comes to the language. So even if a feature is good, I will have a tendency to reject it just on the basis that it makes the language more complex.

I hope this helps, feel free to reach out if you have further questions/concerns.

**Comment by codec-abc** [comment]
Thanks!
