### ISSUE TITLE
Needs a simpler installation path

### ISSUE THREAD

**Issue by svenanders** [skiplang/skip#31]
Prebuilt binaries for Win/Mac/Linux (and/or Brew), or at least a Docker image. Thoughts?

**Comment by pikatchu** [comment]
That's a great idea.

**Comment by SocketByte** [comment]
Yeah, this is the first language that I'm actually struggling to get it working >:(

**Comment by pikatchu** [comment]
That's because we didn't have much time to open-source. I still have a lot of work to do to make Skip easier to use/install :-(

So I created this docker image verlaguet/skip:dev
And I modified the doc to mention it.

It should make everything much easier to build, because it includes all the apt packages that are needed.

I hope this helps.

Any help with packaging npm, apt etc ... would be greatly appreciated :-)

**Comment by pikatchu** [comment]
So the image that I have does not have the binaries installed. It's a good image if you want to work on Skip. Otherwise, if you want to play with the language there is another Docker image (to play).
